### ISSUE TITLE
config files get wrong character in path

### ISSUE THREAD

**Issue by jraller** [tapirdata/generator-webpack-versatile#1]
During installation on a Windows system the `"root": "<%= dirs.tmpDev %>"` in the generator-webpack-versatile/templates/app/root/config/%development.json file gets turned into `"root": ".tmp\dev"` and the backslash d is seen as an illegal character. For the testing.json file the path is seen as `".tmp\test"` where `\t` is interpreted as a tab character.

**Comment by jraller** [comment]
root/builder/dirs.js also has problems with `<%= dirs.serverSrc %>` and `'<%= dirs.clientSrc %>'`

**Comment by andiriedl** [comment]
path issues on Windows are fixed in v2.3.1
